create table translation_cards (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    english text not null,
    meaning text not null,
    translated text not null,
    set_id bigint not null,
    language text not null,
    creator_id uuid not null,
    constraint TranslationCards_pkey primary key (id),
    constraint TranslationCards_creator_id_fkey foreign key (creator_id) references users (uuid) on update cascade on delete cascade,
    constraint TranslationCards_set_id_fkey foreign key (set_id) references sets (id) on update cascade on delete cascade
  ) tablespace pg_default;

create table sets (
    id bigint generated by default as identity not null,
    name text not null,
    page_id bigint not null,
    creator_id uuid null,
    constraint Sets_pkey primary key (id),
    constraint Sets_creator_id_fkey foreign key (creator_id) references users (uuid) on update cascade on delete cascade
  ) tablespace pg_default;

create table users (
    created_at timestamp with time zone not null default now(),
    uuid uuid not null,
    name text not null,
    email text not null,
    constraint Users_pkey primary key (uuid),
    constraint user_uuid_key unique (uuid)
  ) tablespace pg_default;