// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Set struct {
	ID        int64       `json:"id"`
	Name      string      `json:"name"`
	PageID    int64       `json:"page_id"`
	CreatorID pgtype.UUID `json:"creator_id"`
}

type TranslationCard struct {
	ID         int64              `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	English    string             `json:"english"`
	Meaning    string             `json:"meaning"`
	Translated string             `json:"translated"`
	SetID      int64              `json:"set_id"`
	Language   string             `json:"language"`
	CreatorID  pgtype.UUID        `json:"creator_id"`
}

type User struct {
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Uuid      pgtype.UUID        `json:"uuid"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
}
